# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "YOUR_CLIENT_ID"
name = "TidyShelf"
application_url = "https://tidyshelf.omika.ai"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["inventory_levels/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_publications,read_publications"

[auth]
redirect_urls = ["https://tidyshelf.omika.ai/auth/callback"]
